### PR TITLE
ci: Add Expense Contribution workflow

### PR DESCRIPTION
**Pull request by seanpoulter**
### Proposed Changes

- Add workflow from [webdriverio/expense-action](https://github.com/webdriverio/expense-action)

### CODE REVIEW

**Comment by seanpoulter** [comment]
@christian-bromann, I'm not sure if you want this change here or any other pipelines/actions.
Alternatively, we could set this up as a [Starter Workflow](https://docs.github.com/en/actions/using-workflows/creating-starter-workflows-for-your-organization) that would let you configure and commit it to a new repo from **Actions**.

**Comment by christian-bromann** [comment]
Do you know if adding the workflow here will propagate it automatically to all other repositories in this organisation?

> Alternatively, we could set this up as a [Starter Workflow](https://docs.github.com/en/actions/using-workflows/creating-starter-workflows-for-your-organization)

Do you think this is possible to do in `webdriverio/expense-action`?

**Comment by seanpoulter** [comment]
> Do you know if adding the workflow here will propagate it automatically to all other repositories in this organisation?

Unfortunately it doesn't propagate like that. Some folks put their reusable workflows in this directory (like [this blog](https://tech.europace.de/post/github-reusable-workflows-and-how-to-verify-them/)) but I believe we could reference it from webdriverio/expense-action as well.

<br>

> > Alternatively, we could set this up as a [Starter Workflow](https://docs.github.com/en/actions/using-workflows/creating-starter-workflows-for-your-organization)
> 
> Do you think this is possible to do in `webdriverio/expense-action`?

The "starter workflows" have to be defined in the `.github` repository for the organization. Then we'd be presented with an option to add a new Workflow [using the workflow template](https://docs.github.com/en/actions/learn-github-actions/using-starter-workflows#choosing-and-using-a-starter-workflow). It doesn't solve the maintenance problem though.

We could try to automate updates from `webdriverio/expense-action` by adding to **script/**. I tried using the `gh` CLI and it didn't like to `gh pr create` without prompting for user input. 🤦

**Comment by christian-bromann** [comment]
> but I believe we could reference it from webdriverio/expense-action as well.

I think we essentially doing this by referencing it as GitHub Action.

> We could try to automate updates from `webdriverio/expense-action` by adding to **script/**. I tried using the `gh` CLI and it didn't like to `gh pr create` without prompting for user input. 🤦

Yeah, we could have an automated script that clones all repos, commits the given workflow and raises a PR if the workflow has changes but for now I think we can just keep everything as is. If it turns out that we tweak the workflow options a lot, it makes sense to get back to this.

Will close this PR as I don't think we need an expense flow for this particular repository, given we don't expect any non member contributions here. Thanks for all your work!

**Pull request closed without merging**
